"""
Django settings for Organisation project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    "ZTVUosp2rA0KgfETd3pqvnUQUksk0JoQM847Q7fwrdVGXjFjbr206h42tfAHolP2"
    "ceYU12nawHiR8bRGFB64fFS4gv0vbNBqlGN2emsqh9TjsV8O8qhcep3gCoNxIx4Q"
    "zWO7eA953eqUSYoTOqJyzXgVRRH7RMvddH4ZjE7GqMhTCX0OZW31BNKCQtJzYHVz"
    "1Hlml3QV793HokPJIEFTqB9zqS19vkamoHC09tAaNbTzwn0xlmqlK7veNSdW2i46"
    "Xhj9pd0dWWPTTGQozZBSYVHMjEHw0pANzPRdXwNLlWLVcibnN8N6pfkLMfy8di28"
    "V7ivNU88sWLPXXPC3ADBJgY8CZ02PM1F27shjbGuPmVDiWT4OZZe7GwbEnxyT65v"
    "ZxvhjIJmsAmnV1fGpEYzhT9x7bDBg4aYrQe87KiCkV7u0ehsArxJpJt8s029xGXf"
    "UZKJi3VGxUibDfrPk9SRjn1V7FuZG8dhAW2isBNpxwUXAxQTYUvDzngf8VxGVyqA"
    "s6BxJNfEpn60wlI7t5L1gV9TAoiQmH925OFXGdop83yaI2Noyhiu9xHjgXBSOUwg"
    "JtU5mejLmHP3Q6v3SWY5TEgppL3tjKJMhHASHTAeIvioUKp1rucCiCtpsQQdpiyM"
    "Mdlrmcn1l663Q2Qxohbk5RImW3kceoCC2bDAIBukhFoSyaqVdYx7xC9eNwPLpOhp"
    "AQ7n8jdiIJaqAuo6mraeCMlQzpRHZfmLmwxG6XunpylbST4AfG3yNGQW1BEbOgtd"
    "IKNKQcMgMAo94ab1ibr6hxgViHulc1h4EgKzRfBRHDgZ13f9O9W76J0CwNJ4REfs"
    "eoQpmS392hBUS47QgUAv9Wnih0ojmS3z687ZblTUY8iNQp8ZiGMXQeuuvMt85w18"
    "RC5sZFL3CSNQFjgudOwA23qYOeNTS0DAm1qoxzV1AXON8t33q28FcnhgxyRrwsyX"
    "YGD267g2BXFyN6wE1hfNQZs5GeD2vcMrqFjD6mylUfzoH6NmlfmVdyk6O8JglwsC"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
]

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "index.apps.IndexConfig",
    "app_001.apps.App001Config",
    "app_002.apps.App002Config",
    "app_003.apps.App003Config",
    "app_004.apps.App004Config",
    "app_005.apps.App005Config",
    "app_006.apps.App006Config",
    "app_007.apps.App007Config",
    "app_008.apps.App008Config",
    "app_009.apps.App009Config",
    "app_010.apps.App010Config",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "index.middlewares.SimpleMiddleware",
    "index.middlewares.simple_middleware",
]

ROOT_URLCONF = "Organisation.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Organisation.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "postgresql": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "Googol",
        "ATOMIC_REQUESTS": False,
        "AUTOCOMMIT": True,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
        "OPTIONS": {},
        "TIME_ZONE": None,
        "USER": "postgres",
        "PASSWORD": "Windows@11",
        "HOST": "localhost",
        "PORT": "5432",
        "TEST": {
            "CHARSET": None,
            "COLLATION": None,
            "MIGRATE": True,
            "MIRROR": None,
            "NAME": None,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

X_FRAME_OPTIONS = "SAMEORIGIN"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-in"

TIME_ZONE = "Asia/Calcutta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "files" / "static",
]

STATIC_ROOT = BASE_DIR / "static"

STATIC_URL = "static/" if DEBUG else "http://localhost:3000/"

# Media Files

MEDIA_ROOT = BASE_DIR / "files" / "media"

MEDIA_URL = "media/" if DEBUG else "http://localhost:4000/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Enable for deployment

# CSRF_COOKIE_SECURE = True

# SECURE_HSTS_SECONDS = 3600

# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_SSL_REDIRECT = True

# SESSION_COOKIE_SECURE = True

# SECURE_HSTS_PRELOAD = True
