from .Article import ArticleModel
from .Author import AuthorModel
from .Book import BookModel
from .Car import CarModel
from .CarBrand import CarBrandModel
from .CarFuelType import CarFuelTypeModel
from .Category import CategoryModel
from .Demo import DemoModel
from .DemoFK import DemoFKModel
from .DemoM2M import DemoM2MModel
from .DemoO2O import DemoO2OModel
from .Genere import GenereModel
from .Language import LanguageModel
from .Person import PersonModel
from .Pizza import PizzaModel
from .Product import ProductModel
from .Student import StudentModel
from .Tag import TagModel
from .Teacher import TeacherModel
from .Topping import ToppingModel
